CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    category_id INTEGER NOT NULL,
    product_description TEXT,
    rating SMALLINT NOT NULL CHECK(rating BETWEEN 1 AND 5),
    price_excl_tax NUMERIC(10, 2) NOT NULL,
    price_incl_tax NUMERIC(10, 2) NOT NULL,
    tax NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL,
    upc VARCHAR(100) UNIQUE NOT NULL,
    product_type VARCHAR(100),
    number_reviews INTEGER DEFAULT 0,
    url_image TEXT,
    url_product TEXT NOT NULL,

    FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE IF NOT EXISTS authors (
    author_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name VARCHAR(100) NOT NULL,
    birth_year INTEGER,
    country VARCHAR(100),
    external_api_id VARCHAR(200),
    total_known_works INTEGER,
    api_source VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS book_author (
    book_author_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,

    UNIQUE (book_id, author_id),

    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors(author_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_books_rating ON books(rating);
CREATE INDEX IF NOT EXISTS idx_books_category ON books(category_id);
CREATE INDEX IF NOT EXISTS idx_authors_country ON authors(country);
CREATE INDEX IF NOT EXISTS idx_book_author_book ON book_author(book_id;)
CREATE INDEX IF NOT EXISTS idx_book_author_author ON book_author(author_id);
